### PR TITLE
Issue update imports grade entry form

### PR DESCRIPTION
**Pull request by devan-srinivasan**
## Motivation and Context

Rails 6 recently introduced bulk inserts/upserts so I updated this code to accommodate that.

#5280 

## Your Changes

**Description**
I replaced the .import call with a .insert_all instead in the method `create_all_grade_entry_students`

**Type of change** (select all that apply):

 

- [x] Refactoring (internal change to codebase, without changing functionality)

## Testing

I reset the docker container database which uses the method I changed. I ran the spec test suite and the specific file that grades this file separately as well. Lastly, I triggered the UI element that calls the method I changed. All tests passed.

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have fixed any Hound bot comments. 
- [x] I have verified that the TravisCI tests have passed. 
- [x] I have reviewed the test coverage changes reported on Coveralls.

### CODE REVIEW

**Review by david-yz-liu — COMMENTED** [review]
@devan-srinivasan good start, but you can simplify the code further. Since `insert_all` takes a list of hashes, it's easier to modify the original loop (lines 91-94) to accumulate this list directly. Something like

```ruby
new_data = {}

Student.all.each do |student|
  new_data << { ... }
end
```

Note that each hash should have three keys (the ones specified in `columns`), and if you create the hashes manually, you can delete the `columns` variable as well.

Also when you're done you should remove the old code rather than commenting it out.

**Review by david-yz-liu — COMMENTED** [review]
@devan-srinivasan good progress! Two more comments:

1. You still have a line of code commented out, and you should remove it instead.
2. `hound` is an automatic style checker. You should fix all Hound comments. In particular, there needs to be a space inside curly braces `{ ... }`, and instead of `:user_id => ...` you should right `user_id: ...`. The last comment tells you exactly what to change.

**Comment by devan-srinivasan** [comment]
Hey @david-yz-liu how does it look now? I committed this yesterday but just realized maybe I should reply here so you get notified so sorry for the late reply.

**Comment by david-yz-liu** [comment]
@devan-srinivasan don't worry, I get email notifications when pull requests get updated. :) Your PR is definitely looking better, but you missed my first point (about the commented out line).

**Comment by devan-srinivasan** [comment]
Oh my gosh, sorry. Hopefully, it's all good now. I removed that last commented line :)

**Pull request merged**
