### PR TITLE
Prevent concurrent creation of groups for the same student

### PR DESCRIPTION
**Pull request by adisandro**
(the disable_with does not fully work on Safari, it will prevent the double click but won't display the waiting message)

### CODE REVIEW

**Comment by adisandro** [comment]
1. Sure.
2. For blocks, yes. You want it for hashes too? I've never done that so far..

**Comment by david-yz-liu** [comment]
2. Yes, I want this for hashes as well. I should have commented on this earlier, but oh well.

**Comment by adisandro** [comment]
Now that I think about it, I should review the Work Alone function too, I bet there are problems there as well.

**Comment by david-yz-liu** [comment]
@adisandro thanks!

**Pull request merged**
