### PR TITLE
Section due date work

### PR DESCRIPTION
**Pull request by kubasub**
- Added RSpec tests for the `SectionDueDate` model.
- Removed the Test Unit for the `SectionDueDate` model.
- Rewrote `SectionDueDate.due_date_for` method.

I ran both test suites before and after the method rewrite. `0 failures` in all cases.

### CODE REVIEW

**Comment by david-yz-liu** [comment]
@kubasub Yay! Nice to hear from you. One question - why did the schema.db file change like this? Seems like the ":null => false" is a good idea

**Comment by kubasub** [comment]
@david-yz-liu you too!! the schema changes came in when I merged from upstream and `db:migrate`d. The `null: false` is something that I wanted to do, but definitely wasn't me lol.

Do you want me to try to get rid of those mods? I will probably have to play around with it a bit -- possible re-clone/re-fork the repo and reapply my changes.

**Comment by david-yz-liu** [comment]
@kubasub No, I can do it. I ran a db:migrate on your branch and the null: false seemed to come back. Weird.

**Comment by kubasub** [comment]
@david-yz-liu , that's strange. I may have to fix something on my end in the future. I'll keep an eye on that before making a PR.

**Comment by david-yz-liu** [comment]
Quite possibly a version mismatch of rails or something.

**Comment by kubasub** [comment]
@david-yz-liu , just thought I'd tell you that after recreating the db (`db:reset`), `db:migrate` no longer removes the `NOT NULL` constraints.

**Comment by david-yz-liu** [comment]
Good to know, @kubasub! Weird.

**Pull request merged**
