### PR TITLE
Issue#1936 annotation

### PR DESCRIPTION
**Pull request by spring-ryanc**
Turns out I refactored out some support for the multi-line annotations. I wasn't able to recreate the other issue but I tested it pretty thoroughly and found some other small things that snuck by (including one that would have been existing for the previous annotation setup).

### CODE REVIEW

**Comment by spring-ryanc** [comment]
Yikes, I think I got all the major hound fixes. I'm not sure if I should change those two camel cases issues because they are from another class and that might make hound examine it as well. A bunch of these comments were from things I didnt even change

**Comment by david-yz-liu** [comment]
@spring-ryanc I'm okay not fixing those changes (Hound is a bit odd). But the tests are failing - could you look into this?

**Comment by arkon** [comment]
@david-yz-liu You can create a config file based on [the defaults](http://robots.thoughtbot.com/hound-reviews-javascript-for-style-violations) to turn things like camel case variables off.

**Comment by david-yz-liu** [comment]
@spring-ryanc Great job!

**Pull request merged**
