### PR TITLE
Test framework update

### PR DESCRIPTION
**Pull request by jeremygoh**
@david-yz-liu I've made the changes requested to get the sub menu tab for Test Framework to appear again.

Also gotten rid of some merge conflict markers I left behind.

The Test Framework view doesn't currently load because of a number of runtime errors - I tried for an hour to work through these but haven't had much luck. Maybe @WilsonChiang can take a look? Otherwise I'll take a fresh look later today or this weekend. 

Do we want this entire view to be good to go and loading before we merge this PR?

### CODE REVIEW

**Comment by jeremygoh** [comment]
@david-yz-liu @WilsonChiang

**Comment by jeremygoh** [comment]
screen shot 2015-10-09 at 12 15 59 pm

**Comment by david-yz-liu** [comment]
@jeremygoh @WilsonChiang There was a problem in how objects were being passed to the partial.

I fixed the problem here @1663641 (and commented out another problem), but this form really needs a lot of work. Focus on allowing admins to upload at least one test result file, and making sure the updates are actually saved. For now, I don't care if you can only upload one file at a time.

**Comment by jeremygoh** [comment]
Sorry, just realized I didn't reply to this. Thanks! @WilsonChiang and I will look at that functionality this week.

**Pull request merged**
