### PR TITLE
Fix tags not loading

### PR DESCRIPTION
**Pull request by WilsonChiang**
- We are passing a string of the memory address into user.find instead of an actual identifier

part of https://github.com/MarkUsProject/Markus/issues/2274

### CODE REVIEW

**Comment by WilsonChiang** [comment]
So I'm a bit confused at the original intent behind the schema. User is stored as a string. Should this not be an int foreign key to user id? I haven't changed it yet because I can't quite figure out what was happening before... but this should have never worked?

**Comment by david-yz-liu** [comment]
@WilsonChiang Good find. I don't believe your fix is the best possible; I wonder if the problem lies in how Rails is thinking about the `user` attribute for tags. Can you please try instead to add a line to the Tag model that says `belongs_to :user`?

**Comment by WilsonChiang** [comment]
@david-yz-liu 

Seems to complain about a missing `user_id` once I do that. Perhaps I should be changing the schema so that it stores the user_id integer instead?

**Comment by david-yz-liu** [comment]
@WilsonChiang Sorry I didn't reply, but you got it right!

**Pull request merged**
