### PR TITLE
Non-regenerating tokens

### PR DESCRIPTION
**Pull request by MBAustin**
Added option to make tokens never regenerate
Also, gave better names to the “toggle_fields#” series of methods

### CODE REVIEW

**Comment by david-yz-liu** [comment]
@MBAustin I think this is good. Please do a pull from master.

**Comment by MBAustin** [comment]
@david-yz-liu I think this branch is now current with master, but I'm not sure

**Comment by david-yz-liu** [comment]
@MBAustin I need you to do a `git pull upstream master`.

**Comment by MBAustin** [comment]
@david-yz-liu Ok I think now I've done that? Sorry, I'm pretty inexperienced with git (up till now I've just used github desktop, but that messed up somehow). Is it correct now?

**Pull request closed without merging**
