### PR TITLE
fixes issue #1965

### PR DESCRIPTION
**Pull request by ishanthukral**

### CODE REVIEW

**Comment by david-yz-liu** [comment]
This changes the button text in the student submission view (where they go to submit new files). You should make separate text tags for each of the other user adding.

**Comment by ishanthukral** [comment]
@david-yz-liu Hi David, thanks for pointing that out. I thought I had found all uses for it. Should it say "Add New Student" or just "Add New".

**Comment by david-yz-liu** [comment]
I think it should be "Add New Student", "Add New TA", and "Add New Admin". You might want to do a quick search in en.yml; the tags might already exist.

**Comment by ishanthukral** [comment]
@david-yz-liu, I added the new strings for "Add new Admin", "Add new Grader" and "Add new Student". There were existing strings but the words "Grader" and "Admin" were pluralized. I felt that since these links create one new student/admin/grader, they wouldn't be the best suited. Please let me know if you'd like me to user the existing strings instead. Thanks!

**Comment by david-yz-liu** [comment]
Looks great.

**Pull request merged**
