### PR TITLE
config: enable verbose_query_logs in development

### PR DESCRIPTION
**Pull request by david-yz-liu**

### CODE REVIEW

**Comment by adisandro** [comment]
@david-yz-liu does this interfere with bullet? (flyerhzm/bullet#395)

**Comment by david-yz-liu** [comment]
@adisandro it works as expected for me, and I'm on Rails 5.2.1 Can you please try this out and see what you get?

**Comment by adisandro** [comment]
I'm sorry @david-yz-liu I totally forgot about this :(

**Comment by mishaschwartz** [comment]
@david-yz-liu @adisandro Both the server log and the bullet log look ok to me.

For example (no sign of bullet):

```
Started GET "/en/assignments/2/render_feedback_file?feedback_file_id=34" for 127.0.0.1 at 2018-11-30 13:42:25 -0500
Processing by AssignmentsController#render_feedback_file as TEXT
  Parameters: {"feedback_file_id"=>"34", "locale"=>"en", "id"=>"2"}
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/lib/session_handler.rb:15
  FeedbackFile Load (0.6ms)  SELECT  "feedback_files".* FROM "feedback_files" WHERE "feedback_files"."id" = $1 LIMIT $2  [["id", 34], ["LIMIT", 1]]
  ↳ app/controllers/assignments_controller.rb:26
  Rendering text template
  Rendered text template (0.0ms)
Sent data machinefb (0.9ms)
Completed 200 OK in 8ms (Views: 0.7ms | ActiveRecord: 1.5ms)
```

**Comment by adisandro** [comment]
@david-yz-liu @mishaschwartz All good on my system too!

**Pull request merged**
