### PR TITLE
Issue #1834 - Display the absolute final due date

### PR DESCRIPTION
**Pull request by tsimica**
#1834

### CODE REVIEW

**Comment by tsimica** [comment]
Does "absolute due date" or "absolute deadline" make more sense?

**Comment by david-yz-liu** [comment]
@tsimica can you please look into the failing test?

**Comment by reidka** [comment]
I prefer "absolute deadline"

**Comment by reidka** [comment]
Deadline including maximum late penalty
Deadline using all remaining grace tokens

**Comment by tsimica** [comment]
I also added a check to not display "Additional Information" if the grouping was invalid because it didn't make sense to have a field with no value.

**Comment by david-yz-liu** [comment]
@tsimica there should be different messages for whether a late penalty or grace periods are being used.

**Pull request merged**
